// Blocks Network handler for the brain-tech expert-agent network.
//
// One handler serves every agent card in blocks/agents/ — the network tells us
// which agent a task targets via task.agentName, and we delegate to the right
// pipeline in lib/engine.js. Cards generated by `npm run blocks:cards` point
// their runtime.handler at this file.
//
//   - router            -> full multi-expert pipeline (routing, consult, handoff)
//   - orchestrator      -> A2A: fans out to specialist agents over the network
//                          via ctx.taskClient and merges a research brief
//   - expert_<topic>    -> that specialist answers from its own topic cluster
//
// Blocks key concepts implemented here:
//   - Task lifecycle: pending (submitted) -> running (handler starts) ->
//     completed (artifacts returned) | failed (throw) | canceled (cancelSignal)
//   - Progress events via ctx.reportStatus()
//   - requestParts validated against the declared io.inputs[].id ("question")
//   - Outbound bytes stream ("tokens") with token-by-token output
//   - Text + structured JSON artifacts (io.outputs: answer, sources)
import {
  extractQuestion,
  resolveAgent,
  buildStream,
  makeArtifacts,
  runRouter,
  runExpert,
} from './engine.js'
import { runOrchestrator } from './a2a.js'
import { runPaperFeed } from './pipe.js'
import { runPaperUpdates } from './paperupdates.js'
import { runStarMapDemo } from './demo.js'
import { runSotaTracker } from './sota.js'
import { runDatasetFinder } from './datasetfinder.js'
import { runCitationHunter } from './citationhunter.js'
import { runLitReview } from './litreview.js'
import { runGraphExplorer } from './graphexplorer.js'
import { runClinicalTranslator } from './clinical.js'
import { runGrantWriter } from './grantwriter.js'
import { runCodeSuggester } from './codesuggester.js'
import { runAdaSyndicate, runAdaFactCheck, runAdaHarvest } from './ada.js'

export default async function handler(task, ctx) {
  const agentName = task?.agentName || process.env.BLOCKS_AGENT_NAME || 'router'

  // Pipe tasks (long-lived streaming sessions) take a different path: they
  // carry a caller-set duration and stream events until canceled or expired.
  // Only paper_feed (corpus) and paper_updates (live arXiv) declare pipe
  // support; anything else fails fast.
  if (task?.taskKind === 'pipe') {
    if (agentName === 'paper_feed') return runPaperFeed(task, ctx)
    if (agentName === 'paper_updates') return runPaperUpdates(task, ctx)
    throw new Error(`Agent "${agentName}" does not support pipe tasks`)
  }

  // Free demo agent — LLM-free answers + the interactive star-map page as a
  // downloadable text/html artifact. Its input partId is also "question" but
  // it doesn't use the token stream, so handle it before stream setup.
  if (agentName === 'star_map_demo') {
    return runStarMapDemo(task, ctx)
  }

  // Benchmark leaderboard agent — LLM-free SOTA answers from the corpus seed
  // table (data/benchmarks.json). Same input contract, no token stream.
  if (agentName === 'sota_tracker') {
    return runSotaTracker(task, ctx)
  }

  // Datasets directory agent — LLM-free answers from data/datasets.json
  // ("which dataset for motor imagery?"). No stream, instant, zero model cost.
  if (agentName === 'dataset_finder') {
    return runDatasetFinder(task, ctx)
  }

  // Citation-style agent — LLM-free "who cites X?" over the star-map
  // (keyword-co-occurrence proxy, labeled honestly). No stream.
  if (agentName === 'citation_hunter') {
    return runCitationHunter(task, ctx)
  }

  // Graph agent — LLM-free graph reasoning over the star-map (centrality,
  // subgraph, communities, shortest paths). Same contract, no stream.
  if (agentName === 'graph_explorer') {
    return runGraphExplorer(task, ctx)
  }

  // ADA Syndicate — the 15-persona reasoning council. ada_syndicate streams
  // (LLM synthesis); ada_fact_check + ada_harvest are LLM-free, so they run
  // before the stream setup below.
  if (agentName === 'ada_fact_check') {
    return runAdaFactCheck(task, ctx)
  }
  if (agentName === 'ada_harvest') {
    return runAdaHarvest(task, ctx)
  }

  // Validate the input contract up front — a bad task fails fast (failed state)
  // instead of producing a misleading artifact.
  const question = extractQuestion(task)

  // The outbound token stream (null when the network didn't attach one).
  // ada_syndicate tunes buffering per the Stream guide's request example
  // (bundleSizeBytes 2048 / maxLatencyMs 50) so persona tokens reach callers
  // with low latency; other agents keep the SDK defaults.
  const stream = await buildStream(
    ctx,
    agentName === 'ada_syndicate' ? { bundleSizeBytes: 2048, maxLatencyMs: 50 } : undefined,
  )

  const emit = (evt) => {
    if (!evt) return
    switch (evt.type) {
      case 'token':
        if (stream && evt.text) stream.write(evt.text)
        break
      case 'text':
        // Whole-answer chunk for paths that don't emit tokens (cache hits,
        // blocked, INFRA fast paths, deterministic fallback): the caller's
        // stream stays complete even when there's no LLM synthesis.
        if (stream && evt.text) stream.write(evt.text)
        break
      case 'status':
        ctx?.reportStatus(evt.message)
        break
      case 'agent_start':
        ctx?.reportStatus(`${evt.name} is working…`)
        break
      case 'consult':
        ctx?.reportStatus(`Consulting ${evt.to} for a cross-topic answer…`)
        break
      case 'cache':
        ctx?.reportStatus(`Serving from the popular-question cache (${evt.hits} hits)`)
        break
    }
  }

  try {
    if (ctx?.isCancelled) {
      return { artifacts: makeArtifacts('Task was canceled before work started.', []) }
    }

    let result
    if (agentName === 'router') {
      ctx?.reportStatus(`Routing "${question.slice(0, 80)}" to the specialist network…`)
      result = await runRouter(task, ctx, emit)
    } else if (agentName === 'orchestrator') {
      ctx?.reportStatus(`Orchestrating specialist agents for "${question.slice(0, 80)}"…`)
      result = await runOrchestrator(task, ctx, emit)
    } else if (agentName === 'lit_review') {
      ctx?.reportStatus(`Preparing a structured literature review for "${question.slice(0, 80)}"…`)
      result = await runLitReview(task, ctx, emit)
    } else if (agentName === 'clinical_translator') {
      ctx?.reportStatus(`Translating research into clinical practice notes for "${question.slice(0, 80)}"…`)
      result = await runClinicalTranslator(task, ctx, emit)
    } else if (agentName === 'grant_writer') {
      ctx?.reportStatus(`Drafting a proposal for "${question.slice(0, 80)}"…`)
      result = await runGrantWriter(task, ctx, emit)
    } else if (agentName === 'code_suggester') {
      ctx?.reportStatus(`Sketching a PyTorch skeleton for "${question.slice(0, 80)}"…`)
      result = await runCodeSuggester(task, ctx, emit)
    } else if (agentName === 'ada_syndicate') {
      result = await runAdaSyndicate(task, ctx, emit)
    } else {
      const agent = resolveAgent(agentName)
      result = await runExpert(agent, task, ctx, emit)
    }

    if (stream) await stream.end()

    // Router path: ask() may return an empty answer when canceled mid-flight.
    if (ctx?.isCancelled && !result.answer) {
      ctx?.reportStatus('Task canceled — no answer was produced.')
      return { artifacts: makeArtifacts('(Task was canceled before an answer was produced.)', []) }
    }

    // Orchestrator path: additionally attach the structured per-specialist
    // report as a third artifact (io.outputs.report).
    // lit_review path: attach the structured review JSON (io.outputs.review).
    const artifacts = makeArtifacts(result.answer, result.sources)
    if (result.report) {
      artifacts.push({
        data: JSON.stringify(result.report, null, 2),
        mimeType: 'application/json',
        outputId: 'report',
        fileName: 'report.json',
      })
    }
    if (result.review) {
      artifacts.push({
        data: JSON.stringify(result.review, null, 2),
        mimeType: 'application/json',
        outputId: 'review',
        fileName: 'review.json',
      })
    }
    if (result.draft) {
      artifacts.push({
        data: JSON.stringify(result.draft, null, 2),
        mimeType: 'application/json',
        outputId: 'draft',
        fileName: 'draft.json',
      })
    }
    if (result.skeleton) {
      artifacts.push({
        data: JSON.stringify(result.skeleton, null, 2),
        mimeType: 'application/json',
        outputId: 'skeleton',
        fileName: 'skeleton.json',
      })
    }
    if (result.ada) {
      artifacts.push({
        data: JSON.stringify(result.ada, null, 2),
        mimeType: 'application/json',
        outputId: 'ada',
        fileName: 'ada.json',
      })
    }
    return { artifacts }
  } catch (err) {
    // A canceled task returns partial output; only genuine failures end in the
    // failed lifecycle state.
    if (err?.name === 'AbortError' || ctx?.cancelSignal?.aborted || ctx?.isCancelled) {
      if (stream) await stream.end().catch(() => {})
      return { artifacts: makeArtifacts('(Task was canceled before an answer was produced.)', []) }
    }
    if (stream) await stream.end().catch(() => {})
    throw new Error(`Agent "${agentName}" failed: ${err.message}`)
  }
}
