// Blocks Network handler for the brain-tech expert-agent network.
//
// One handler serves every agent card in blocks/agents/ — the network tells us
// which agent a task targets via task.agentName, and we delegate to the right
// pipeline in lib/engine.js. Cards generated by `npm run blocks:cards` point
// their runtime.handler at this file.
//
//   - router            -> full multi-expert pipeline (routing, consult, handoff)
//   - orchestrator      -> A2A: fans out to specialist agents over the network
//                          via ctx.taskClient and merges a research brief
//   - expert_<topic>    -> that specialist answers from its own topic cluster
//
// Blocks key concepts implemented here:
//   - Task lifecycle: pending (submitted) -> running (handler starts) ->
//     completed (artifacts returned) | failed (throw) | canceled (cancelSignal)
//   - Progress events via ctx.reportStatus()
//   - requestParts validated against the declared io.inputs[].id ("question")
//   - Outbound bytes stream ("tokens") with token-by-token output
//   - Text + structured JSON artifacts (io.outputs: answer, sources)
import {
  extractQuestion,
  resolveAgent,
  buildStream,
  makeArtifacts,
  runRouter,
  runExpert,
} from './engine.js'
import { runOrchestrator } from './a2a.js'
import { runPaperFeed } from './pipe.js'
import { runStarMapDemo } from './demo.js'

export default async function handler(task, ctx) {
  const agentName = task?.agentName || process.env.BLOCKS_AGENT_NAME || 'router'

  // Pipe tasks (long-lived streaming sessions) take a different path: they
  // carry a caller-set duration and stream events until canceled or expired.
  // Only paper_feed declares pipe support; anything else fails fast.
  if (task?.taskKind === 'pipe') {
    if (agentName !== 'paper_feed') {
      throw new Error(`Agent "${agentName}" does not support pipe tasks`)
    }
    return runPaperFeed(task, ctx)
  }

  // Free demo agent — LLM-free answers + the interactive star-map page as a
  // downloadable text/html artifact. Its input partId is also "question" but
  // it doesn't use the token stream, so handle it before stream setup.
  if (agentName === 'star_map_demo') {
    return runStarMapDemo(task, ctx)
  }

  // Validate the input contract up front — a bad task fails fast (failed state)
  // instead of producing a misleading artifact.
  const question = extractQuestion(task)

  // The outbound token stream (null when the network didn't attach one).
  const stream = await buildStream(ctx)

  const emit = (evt) => {
    if (!evt) return
    switch (evt.type) {
      case 'token':
        if (stream && evt.text) stream.write(evt.text)
        break
      case 'status':
        ctx?.reportStatus(evt.message)
        break
      case 'agent_start':
        ctx?.reportStatus(`${evt.name} is working…`)
        break
      case 'consult':
        ctx?.reportStatus(`Consulting ${evt.to} for a cross-topic answer…`)
        break
      case 'cache':
        ctx?.reportStatus(`Serving from the popular-question cache (${evt.hits} hits)`)
        break
    }
  }

  try {
    if (ctx?.isCancelled) {
      return { artifacts: makeArtifacts('Task was canceled before work started.', []) }
    }

    let result
    if (agentName === 'router') {
      ctx?.reportStatus(`Routing "${question.slice(0, 80)}" to the specialist network…`)
      result = await runRouter(task, ctx, emit)
    } else if (agentName === 'orchestrator') {
      ctx?.reportStatus(`Orchestrating specialist agents for "${question.slice(0, 80)}"…`)
      result = await runOrchestrator(task, ctx, emit)
    } else {
      const agent = resolveAgent(agentName)
      result = await runExpert(agent, task, ctx, emit)
    }

    if (stream) await stream.end()

    // Router path: ask() may return an empty answer when canceled mid-flight.
    if (ctx?.isCancelled && !result.answer) {
      ctx?.reportStatus('Task canceled — no answer was produced.')
      return { artifacts: makeArtifacts('(Task was canceled before an answer was produced.)', []) }
    }

    // Orchestrator path: additionally attach the structured per-specialist
    // report as a third artifact (io.outputs.report).
    const artifacts = makeArtifacts(result.answer, result.sources)
    if (result.report) {
      artifacts.push({
        data: JSON.stringify(result.report, null, 2),
        mimeType: 'application/json',
        outputId: 'report',
        fileName: 'report.json',
      })
    }
    return { artifacts }
  } catch (err) {
    // A canceled task returns partial output; only genuine failures end in the
    // failed lifecycle state.
    if (err?.name === 'AbortError' || ctx?.cancelSignal?.aborted || ctx?.isCancelled) {
      if (stream) await stream.end().catch(() => {})
      return { artifacts: makeArtifacts('(Task was canceled before an answer was produced.)', []) }
    }
    if (stream) await stream.end().catch(() => {})
    throw new Error(`Agent "${agentName}" failed: ${err.message}`)
  }
}
