// Generated by `blocks init ui --mode webapp` and customized for the
// Brain Star Map research console. The embed-auth plumbing below is the
// part of the scaffold that must be kept intact — sign-in, auto-resume,
// sign-out, and error mapping are unchanged from the generated file.
//
// Everything below the auth block (agent nav, composer, artifact
// rendering) is data-driven from the AGENTS table, which mirrors each
// agent card's inputs/outputs/streams snapshot from init time.

// ---------------------------------------------------------------------------
// Auth block (generated scaffold — keep verbatim)
// ---------------------------------------------------------------------------

(function () {
  const signInBtn = document.getElementById('sign-in-btn');
  const gateSignInBtn = document.getElementById('gate-sign-in-btn');
  const signOutBtn = document.getElementById('sign-out-btn');
  const authError = document.getElementById('auth-error');

  // Map an error to a user-visible message. Used by both the sign-in
  // catch (where errors are typically BlocksAuthError from the popup
  // flow) and per-send catches (where InsufficientBalance comes from
  // the backend RPC for paid agents the caller can't afford). One source
  // of truth so the two catches stay in sync.
  function blocksErrorMessage(err) {
    if (typeof BlocksAuth === 'undefined') {
      return 'The Blocks auth widget failed to load. Check your network connection and reload.';
    }
    if (err instanceof BlocksAuth.BlocksAuthError) {
      return 'Sign-in error: ' + err.message;
    }
    if (err && err.data && err.data.code === 'InsufficientBalance') {
      return 'This agent requires funds to use. Add a balance in your Blocks dashboard.';
    }
    return 'Unexpected error: ' + (err && err.message ? err.message : String(err));
  }

  // Render an artifact's bytes into outputEl based on its own mimeType.
  // Used for: (a) untagged artifacts (event.outputId may be undefined per
  // SDK_CONTRACT §9.1), (b) outputId values that don't match any declared
  // output, (c) the post-terminal listArtifacts() defensive fallback.
  function renderArtifactByMime(bytes, mimeType, outputEl) {
    const mt = mimeType || '';
    if (mt === 'application/json') {
      try {
        const parsed = JSON.parse(new TextDecoder().decode(bytes));
        outputEl.textContent += JSON.stringify(parsed, null, 2);
        return;
      } catch (_) {
        outputEl.textContent += new TextDecoder().decode(bytes);
        return;
      }
    }
    if (mt === 'text/html') {
      const blob = new Blob([bytes], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'star-map-demo.html';
      a.textContent = '⬇ Download star-map-demo.html (interactive 3D star map)'; 
      a.className = 'detail-link';
      outputEl.appendChild(a);
      return;
    }
    if (mt.indexOf('text/') === 0) {
      outputEl.textContent += new TextDecoder().decode(bytes);
      return;
    }
    if (mt.indexOf('image/') === 0) {
      const blob = new Blob([bytes], { type: mt });
      const img = document.createElement('img');
      img.className = 'output';
      img.src = URL.createObjectURL(blob);
      outputEl.appendChild(img);
      return;
    }
    const blob = new Blob([bytes], mt ? { type: mt } : undefined);
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'artifact';
    link.textContent = 'Download artifact' + (mt ? ' (' + mt + ')' : '');
    outputEl.appendChild(link);
  }

  // Maximum time to wait for the embed-auth widget script (injected in
  // index.html) to define window.BlocksAuth.
  const WIDGET_READY_TIMEOUT_MS = 10000;

  // Resolve once the widget has defined window.BlocksAuth, or to false after
  // WIDGET_READY_TIMEOUT_MS if it never loads. The widget is a large
  // cross-origin bundle injected via a dynamically-created <script>; a
  // dynamically-inserted async=false script is NOT ordered against this
  // deferred app.js, so app.js can run first. Reading window.BlocksAuth
  // synchronously would then see it undefined. Wait instead of assuming.
  function whenBlocksAuthReady(timeoutMs) {
    return new Promise(function (resolve) {
      if (typeof BlocksAuth !== 'undefined') { resolve(true); return; }
      let waited = 0;
      const step = 50;
      const timer = setInterval(function () {
        if (typeof BlocksAuth !== 'undefined') {
          clearInterval(timer);
          resolve(true);
        } else if ((waited += step) >= timeoutMs) {
          clearInterval(timer);
          resolve(false);
        }
      }, step);
    });
  }

  // Multi-agent scaffold: signInAndGetClients returns one TaskClient per agent.
  // The agent set is the scope of the embed-auth session (partition key), so
  // adding an agent here means re-consenting once; the refresh token then
  // covers the whole set for 24h.
  const AGENT_IDS = ["router", "orchestrator", "expert_connectomics", "expert_bci_eeg", "expert_deep_learning", "expert_neural_decoding", "expert_clinical_apps", "expert_other", "paper_feed", "paper_updates", "star_map_demo", "sota_tracker", "dataset_finder", "citation_hunter", "graph_explorer", "lit_review", "clinical_translator", "grant_writer", "code_suggester", "ada_syndicate", "ada_fact_check", "ada_harvest", "my_echo", "my_adder", "my_orchestrator"];

  let clients = null;

  function embedBackendBaseUrl() {
    const dev = (typeof window !== 'undefined' && window.__BLOCKS_EMBED_DEV__) || null;
    return (dev && dev.backendBaseUrl) ? dev.backendBaseUrl : "https://app.blocks.ai";
  }

  async function attemptSignIn() {
    authError.textContent = '';
    if (!(await whenBlocksAuthReady(WIDGET_READY_TIMEOUT_MS))) {
      authError.textContent = 'The Blocks auth widget failed to load. Check your network connection and reload.';
      return false;
    }
    try {
      clients = await BlocksAuth.signInAndGetClients({ agents: AGENT_IDS, backendBaseUrl: embedBackendBaseUrl() });
      window.__blocksClients = clients; // exposed for debugging
      signInBtn.hidden = true;
      gateSignInBtn.hidden = true;
      signOutBtn.hidden = false;
      onSignedIn();
      return true;
    } catch (err) {
      authError.textContent = blocksErrorMessage(err);
      pendingShowcase = null; // a cancelled/failed sign-in must not fire a stale showcase later
      return false;
    }
  }

  signInBtn.addEventListener('click', attemptSignIn);
  if (gateSignInBtn) gateSignInBtn.addEventListener('click', attemptSignIn);

  // Auto-resume on page load: silent refresh ONLY when the stored partition exactly matches this page's (backend, origin, agents); otherwise wait for click.
  async function hasExactStoredEmbedSession() {
    try {
      if (typeof BlocksAuth === 'undefined' || typeof BlocksAuth.computePartitionKey !== 'function') return false;
      const raw = localStorage.getItem('blocks-auth-active-sessions-v1');
      if (!raw) return false;
      const arr = JSON.parse(raw);
      if (!Array.isArray(arr) || arr.length === 0) return false;
      const backendBaseUrl = embedBackendBaseUrl();
      const pageOrigin = window.location.origin;
      const agentNames = AGENT_IDS;
      const expected = await BlocksAuth.computePartitionKey({ backendBaseUrl, pageOrigin, agentNames });
      return arr.some(function (entry) { return entry && entry.partitionKey === expected; });
    } catch (_) {
      return false;
    }
  }
  whenBlocksAuthReady(WIDGET_READY_TIMEOUT_MS).then(function () {
    hasExactStoredEmbedSession().then(function (yes) {
      if (yes) attemptSignIn();
    });
  });

  signOutBtn.addEventListener('click', async () => {
    // signOut clears the partitioned localStorage entry for this origin;
    // reload to reset the in-page state.
    await BlocksAuth.signOut();
    window.location.reload();
  });

// ---------------------------------------------------------------------------
// Agent config (mirrors card snapshots from `blocks init`)
// ---------------------------------------------------------------------------

  const AGENTS = [
    {
      id: 'router',
      label: 'Research Router',
      tagline: 'Answers questions across the full 215-paper corpus with citations.',
      color: '#0f52ba',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 4, hint: 'A research question about the brain-technology corpus (citations returned as [n]).',
          default: 'What are the best EEG motor-imagery decoding methods?' }
      ]
    },
    {
      id: 'orchestrator',
      label: 'A2A Orchestrator',
      tagline: 'Auto-routes a question to every relevant topic expert (up to all six) in parallel, merges their briefs.',
      color: '#8b5cf6',
      kind: 'research',
      outputs: ['answer', 'sources', 'report'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 4, hint: 'A research question about the brain-technology corpus.',
          default: 'What are the best EEG motor-imagery decoding methods?' },
        { id: 'specialists', label: 'Specialists (optional)', rows: 1, hint: 'Comma-separated agent names to call in parallel. Leave empty to auto-route to the top-2 experts.',
          default: 'expert_connectomics,expert_bci_eeg' }
      ]
    },
    {
      id: 'expert_connectomics',
      label: 'Connectomics Expert',
      tagline: 'Specialist answers grounded in the connectomics / neural-decoding cluster.',
      color: '#10b981',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 4, hint: 'A research question for this specialist.',
          default: 'What are graph neural networks used for in connectomics?' }
      ]
    },
    {
      id: 'expert_bci_eeg',
      label: 'BCI & EEG Expert',
      tagline: 'Specialist answers grounded in the BCI / EEG decoding cluster.',
      color: '#e0115f',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 4, hint: 'A research question for this specialist.',
          default: 'What are the best EEG motor-imagery decoding methods?' }
      ]
    },
    {
      id: 'expert_deep_learning',
      label: 'Deep Learning Expert',
      tagline: 'Specialist answers grounded in the deep-learning methods cluster.',
      color: '#eab308',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 4, hint: 'A research question for this specialist.',
          default: 'What deep learning architectures are used for EEG decoding?' }
      ]
    },
    {
      id: 'expert_neural_decoding',
      label: 'Neural Decoding Expert',
      tagline: 'Specialist answers grounded in the neural-decoding cluster.',
      color: '#6366f1',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 4, hint: 'A research question for this specialist.',
          default: 'How is motor imagery decoded from EEG?' }
      ]
    },
    {
      id: 'expert_clinical_apps',
      label: 'Clinical Apps Expert',
      tagline: 'Specialist answers grounded in the clinical / rehabilitation cluster.',
      color: '#f97316',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 4, hint: 'A research question for this specialist.',
          default: 'What BCI systems are used in stroke rehabilitation?' }
      ]
    },
    {
      id: 'expert_other',
      label: 'Other Topics Expert',
      tagline: 'Specialist answers grounded in the remaining corpus topics.',
      color: '#64748b',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 4, hint: 'A research question for this specialist.',
          default: 'What are the main research topics in this corpus?' }
      ]
    },
    {
      id: 'paper_feed',
      label: 'Paper Feed (live stream)',
      tagline: 'Pipe agent — streams corpus papers matching a topic as live events for the session duration.',
      color: '#0d9488',
      kind: 'pipe',
      outputs: ['summary'],
      hasStream: false,
      inputs: [
        { id: 'topic', label: 'Topic', rows: 2, hint: 'Keyword/phrase to match against the corpus.',
          default: 'EEG motor imagery' },
        { id: 'duration', label: 'Duration (minutes)', type: 'number', rows: 1, hint: 'Pipe session length: 1 minute – 30 days. Events stream until you stop or it expires.',
          default: '1' }
      ]
    },
    {
      id: 'star_map_demo',
      label: 'Star Map Demo (free)',
      tagline: 'Free demo agent — instant LLM-free corpus answers, plus the interactive 3D star-map page as a downloadable HTML artifact.',
      color: '#22d3ee',
      kind: 'demo',
      outputs: ['answer', 'demo', 'sources'],
      hasStream: false,
      inputs: [
        { id: 'question', label: 'Question', rows: 2, hint: 'Ask about the corpus (e.g. "how many papers?") or type "show the demo". No language model — instant + free.',
          default: 'How many papers are in the corpus?' }
      ]
    },
    {
      id: 'my_echo',
      label: 'Echo (demo)',
      tagline: 'A2A guide demo — echoes your text back.',
      color: '#f59e0b',
      kind: 'demo',
      outputs: ['echo'],
      hasStream: false,
      inputs: [
        { id: 'request', label: 'Text to echo', rows: 2, hint: 'Plain text.',
          default: 'Hello!' }
      ]
    },
    {
      id: 'my_adder',
      label: 'Adder (demo)',
      tagline: 'A2A guide demo — adds two numbers.',
      color: '#14b8a6',
      kind: 'demo',
      outputs: ['sum'],
      hasStream: false,
      inputs: [
        { id: 'request', label: 'Addend JSON', rows: 2, hint: 'JSON like {"kind":"math_add","a":3,"b":4}.',
          default: '{"kind":"math_add","a":3,"b":4}' }
      ]
    },
    {
      id: 'my_orchestrator',
      label: 'Mini Orchestrator (demo)',
      tagline: 'A2A guide demo — dispatches fixed sub-tasks to my_echo and my_adder, merges results.',
      color: '#ec4899',
      kind: 'demo',
      outputs: ['merged'],
      hasStream: false,
      inputs: [
        { id: 'request', label: 'Trigger', rows: 2, hint: 'Any text; the orchestrator runs its fixed pipeline.',
          default: 'Run the demo' }
      ]
    },
    {
      id: 'sota_tracker',
      label: 'SOTA Tracker',
      tagline: 'LLM-free — benchmark leaderboard: "what\u2019s the SOTA on BCI IV-2a?" with ranked self-reported results.',
      color: '#f59e0b',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: false,
      inputs: [
        { id: 'question', label: 'Question', rows: 3, hint: 'A SOTA / leaderboard question, e.g. "best accuracy on BCI IV-2a" or "all benchmarks".',
          default: 'What is the state of the art on BCI IV-2a?' }
      ]
    },
    {
      id: 'dataset_finder',
      label: 'Dataset Finder',
      tagline: 'LLM-free — which dataset for your task? Cards with modality, subjects, benchmark SOTA and corpus users.',
      color: '#22c55e',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: false,
      inputs: [
        { id: 'question', label: 'Question', rows: 3, hint: 'e.g. "which dataset for motor imagery?", "dataset for seizure detection", "details on WAY-EEG-GAL", "all datasets".',
          default: 'Which dataset should I use for cross-subject motor imagery decoding?' }
      ]
    },
    {
      id: 'citation_hunter',
      label: 'Citation Hunter',
      tagline: 'LLM-free — "who cites X?" over the star-map. Keyword-proxy edges, labeled honestly.',
      color: '#a78bfa',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: false,
      inputs: [
        { id: 'question', label: 'Question', rows: 3, hint: 'e.g. "most cited papers in Connectomics", "who cites <paper>?", "how many connections does <paper> have?".',
          default: 'Most cited papers in Connectomics' }
      ]
    },
    {
      id: 'graph_explorer',
      label: 'Graph Explorer',
      tagline: 'LLM-free — centrality, subgraphs, communities, bridges and paths over the star-map graph.',
      color: '#2dd4bf',
      kind: 'research',
      outputs: ['answer', 'subgraph', 'sources'],
      hasStream: false,
      inputs: [
        { id: 'question', label: 'Question', rows: 3, hint: 'e.g. "most central papers in Connectomics", "subgraph around <paper>", "shortest path between <A> and <B>".',
          default: 'Most central papers in Connectomics' }
      ]
    },
    {
      id: 'lit_review',
      label: 'Lit Review ($0.10)',
      tagline: 'Multi-hop structured literature review — OVERVIEW / METHOD COMPARISON / KEY FINDINGS / GAPS with citations.',
      color: '#38bdf8',
      kind: 'research',
      outputs: ['answer', 'sources', 'review'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 3, hint: 'A research question for a structured review with [n] citations.',
          default: 'Compare Riemannian and deep-learning decoders for motor imagery' },
        { id: 'focus', label: 'Focus (optional)', rows: 1, hint: 'Sharpen the comparison axes, e.g. "focus on cross-subject generalization".',
          default: '' }
      ]
    },
    {
      id: 'clinical_translator',
      label: 'Clinical Translator',
      tagline: 'Paper findings \u2192 plain-language practice notes for stroke rehab, CP, neurofeedback.',
      color: '#fb923c',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 3, hint: 'Ask about clinical applications in plain terms.',
          default: 'What does recent EEG research mean for stroke rehabilitation?' }
      ]
    },
    {
      id: 'grant_writer',
      label: 'Grant Writer ($0.10)',
      tagline: 'Research idea \u2192 proposal draft (TITLE / BACKGROUND / RELATED WORK / CONTRIBUTION / RISKS) with citations.',
      color: '#f472b6',
      kind: 'research',
      outputs: ['answer', 'sources', 'draft'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Research idea', rows: 3, hint: 'Describe the research idea for the proposal draft.',
          default: 'Combine foundation models with Riemannian decoding for cross-subject EEG' }
      ]
    },
    {
      id: 'code_suggester',
      label: 'Code Suggester',
      tagline: 'Method or idea \u2192 PyTorch architecture skeleton with citations (unverified outline).',
      color: '#34d399',
      kind: 'research',
      outputs: ['answer', 'sources', 'skeleton'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Method / idea', rows: 3, hint: 'What architecture should be sketched? Cite-checked against the corpus.',
          default: 'Sketch a CNN-LSTM architecture for motor imagery decoding' }
      ]
    },
    {
      id: 'ada_syndicate',
      label: 'ADA Syndicate (15 personas)',
      tagline: 'Routes your question to one of 15 reasoning personas — bias, ethics, incentives, paradoxes, long-term forecasting, neurodivergent translation, preregistration & more. Security-swept, cached, knowledge-base grounded.',
      color: '#e879f9',
      kind: 'research',
      outputs: ['answer', 'sources', 'ada'],
      hasStream: true,
      inputs: [
        { id: 'question', label: 'Question', rows: 3, hint: 'Ask anything; the syndicate auto-routes to the best persona by intent.',
          default: 'How do I stop perverse incentives in an LLM marketplace?' },
        { id: 'agent_id', label: 'Persona (optional)', rows: 1, hint: 'One of: bias_mitigator, alignment_auditor, incentive_architect, epistemic_humility, nudge_designer, paradox_resolver, trauma_analyst, ontology_mapper, adversarial_sim, longterm_forecaster, neuro_translator, resource_allocator, consensus_builder, semiotics_decoder, prereg_enforcer. Empty = auto-route.',
          default: '' }
      ]
    },
    {
      id: 'ada_fact_check',
      label: 'ADA Fact Check',
      tagline: 'LLM-free — checks a DOI (or ADA knowledge-base paper) for retraction / validity status.',
      color: '#fbbf24',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: false,
      inputs: [
        { id: 'question', label: 'DOI or paper title', rows: 2, hint: 'A DOI (e.g. 10.1103/PhysRevE.112) or an ADA knowledge-base paper title.',
          default: '10.1103/PhysRevE.112' }
      ]
    },
    {
      id: 'ada_harvest',
      label: 'ADA Harvest (arXiv)',
      tagline: 'LLM-free — the Paper Agent: scrapes the NEWEST arXiv papers on a topic, star-map formatted.',
      color: '#4ade80',
      kind: 'research',
      outputs: ['answer', 'sources'],
      hasStream: false,
      inputs: [
        { id: 'topic', label: 'Topic', rows: 2, hint: 'Keyword/phrase for the live arXiv search.',
          default: 'mechanism design' }
      ]
    },
    {
      id: 'paper_updates',
      label: 'Paper Updates (live arXiv)',
      tagline: 'Pipe agent — streams the NEWEST arXiv submissions on a topic as live events; fresh papers picked up live.',
      color: '#06b6d4',
      kind: 'pipe',
      outputs: ['summary'],
      hasStream: false,
      inputs: [
        { id: 'topic', label: 'Topic', rows: 2, hint: 'Keyword/phrase for the live arXiv query (comma-separated terms are OR-ed).',
          default: 'brain-computer interface, motor imagery' },
        { id: 'duration', label: 'Duration (minutes)', type: 'number', rows: 1, hint: 'Pipe session length: 1 minute – 30 days. Events stream until you stop or it expires.',
          default: '1' }
      ]
    }
  ];

  let currentAgent = AGENTS[0];

  // DOM handles
  const navEl = document.getElementById('agent-nav');
  const cardTitle = document.getElementById('agent-title');
  const cardTagline = document.getElementById('agent-tagline');
  const cardOrb = document.getElementById('agent-orb');
  const cardBadges = document.getElementById('agent-badges');
  const cardKind = document.getElementById('agent-kind');
  const composer = document.getElementById('composer');
  const composerInputs = document.getElementById('composer-inputs');
  const sendBtn = document.getElementById('send-btn');
  const statusLine = document.getElementById('status-line');
  const answerArea = document.getElementById('answer-area');
  const answerText = document.getElementById('answer-text');
  const answerState = document.getElementById('answer-state');
  const sourcesArea = document.getElementById('sources-area');
  const sourcesList = document.getElementById('sources-list');
  const reportArea = document.getElementById('report-area');
  const reportText = document.getElementById('report-text');
  const demoArea = document.getElementById('demo-area');
  const demoText = document.getElementById('demo-text');

  function el(tag, className, text) {
    const node = document.createElement(tag);
    if (className) node.className = className;
    if (text !== undefined) node.textContent = text;
    return node;
  }

  function setStatus(text, working) {
    if (!text) { statusLine.hidden = true; return; }
    statusLine.hidden = false;
    statusLine.textContent = text;
    statusLine.classList.toggle('working', !!working);
  }

  function resetOutputs() {
    resetStarMapDemo && resetStarMapDemo();
    lastSourcesData = [];
    lastAnswerText = '';
    answerArea.hidden = true;
    answerText.textContent = '';
    answerState.textContent = '';
    answerState.style.color = '';
    sourcesArea.hidden = true;
    sourcesList.textContent = '';
    reportArea.hidden = true;
    reportText.textContent = '';
    demoArea.hidden = true;
    demoText.textContent = '';
    setStatus('', false);
  }

  function markCitations(node) {
    // Turn [n] and [n,m] markers into styled spans.
    if (node.querySelector('.cite')) return;
    const walker = document.createTreeWalker(node, NodeFilter.SHOW_TEXT);
    const targets = [];
    while (walker.nextNode()) targets.push(walker.currentNode);
    for (const t of targets) {
      const frag = document.createDocumentFragment();
      const parts = t.textContent.split(/(\[\d+(?:,\s*\d+)*\])/g);
      for (const part of parts) {
        if (/^\[\d+(?:,\s*\d+)*\]$/.test(part)) {
          const span = el('span', 'cite', part);
          frag.appendChild(span);
        } else if (part) {
          frag.appendChild(document.createTextNode(part));
        }
      }
      t.parentNode.replaceChild(frag, t);
    }
  }

  function renderSources(data) {
    const arr = Array.isArray(data) ? data : (data && data.sources) || [];
    if (!arr.length) return;
    lastSourcesData = arr;
    sourcesArea.hidden = false;
    sourcesList.textContent = '';
    arr.forEach(function (src, i) {
      const a = el('a');
      if (src.url) { a.href = src.url; a.target = '_blank'; a.rel = 'noreferrer'; }
      a.appendChild(el('span', 'src-idx', '[' + (i + 1) + ']'));
      a.appendChild(el('span', 'src-title', src.title || 'Untitled'));
      if (src.year) a.appendChild(el('span', 'src-year', String(src.year)));
      if (src.url) a.appendChild(el('span', 'src-ext', '↗'));
      sourcesList.appendChild(a);
    });
  }

  // -------------------------------------------------------------------------
  // Exports (BibTeX / CSV / copy-brief) + showcase quick actions + free funnel
  // -------------------------------------------------------------------------
  let lastSourcesData = [];
  let lastAnswerText = '';
  let pendingShowcase = null;

  function downloadText(filename, text, mime) {
    const blob = new Blob([text], mime ? { type: mime } : undefined);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  function exportBibtex() {
    if (!lastSourcesData.length) return;
    const entries = lastSourcesData.map(function (s, i) {
      const key = 'sm' + (i + 1);
      const authors = (s.authors && s.authors.length) ? s.authors.join(' and ') : (s.first_author || 'Unknown');
      const year = s.year || 'n.d.';
      return '@misc{' + key + ',\n  title = {' + (s.title || 'Untitled') + '},\n  author = {' + authors + '},\n  year = {' + year + '},\n  url = {' + (s.url || '') + '}\n}';
    }).join('\n\n');
    downloadText('brain-star-map-sources.bib', entries, 'text/plain');
  }

  function exportCsv() {
    if (!lastSourcesData.length) return;
    const esc = function (v) { return '"' + String(v == null ? '' : v).replace(/"/g, '""') + '"'; };
    const rows = [['#', 'title', 'authors', 'year', 'url'].map(esc).join(',')];
    lastSourcesData.forEach(function (s, i) {
      rows.push([i + 1, s.title, s.authors ? s.authors.join('; ') : s.first_author, s.year, s.url].map(esc).join(','));
    });
    downloadText('brain-star-map-sources.csv', rows.join('\n'), 'text/csv');
  }

  async function copyBrief() {
    if (!lastAnswerText && !lastSourcesData.length) return;
    let md = lastAnswerText || '';
    if (lastSourcesData.length) {
      md += '\n\n---\nSources:\n' + lastSourcesData.map(function (s, i) {
        return (i + 1) + '. ' + (s.title || 'Untitled') + (s.year ? ' (' + s.year + ')' : '') + (s.url ? ' — ' + s.url : '');
      }).join('\n');
    }
    try {
      await navigator.clipboard.writeText(md);
      const btn = document.getElementById('copy-brief-btn');
      if (btn) {
        const old = btn.textContent;
        btn.textContent = 'Copied ✓';
        setTimeout(function () { btn.textContent = old; }, 1500);
      }
    } catch (_) { /* clipboard unavailable — ignore */ }
  }

  // One-click quick actions: select the agent, prefill, and send. Doubles as
  // the free-funnel (star_map_demo needs no funds) and the A2A showcase.
  const SHOWCASE = [
    { agent: 'orchestrator', label: 'A2A deep-dive', question: 'Compare connectomics and deep learning approaches in brain research', icon: '⚡', tag: '6 experts in parallel' },
    { agent: 'lit_review', label: 'Literature review', question: 'Compare Riemannian and deep-learning decoders for motor imagery', icon: '📚', tag: '$0.10' },
    { agent: 'sota_tracker', label: 'SOTA leaderboard', question: 'What is the state of the art on BCI IV-2a?', icon: '🏆', tag: 'LLM-free' },
    { agent: 'dataset_finder', label: 'Find a dataset', question: 'Which dataset should I use for cross-subject motor imagery decoding?', icon: '🗂', tag: 'LLM-free' },
    { agent: 'graph_explorer', label: 'Graph explorer', question: 'Most central papers in Connectomics', icon: '✦', tag: 'LLM-free' },
    { agent: 'code_suggester', label: 'PyTorch skeleton', question: 'Sketch a CNN-LSTM architecture for motor imagery decoding', icon: '⌘', tag: 'LLM' },
    { agent: 'ada_syndicate', label: 'ADA Syndicate', question: 'How do I stop perverse incentives in an LLM marketplace?', icon: '🧠', tag: '15 personas' },
    { agent: 'star_map_demo', label: 'Free demo', question: 'Show me the demo', icon: '✧', tag: 'FREE · no funds needed' },
  ];

  function buildShowcase() {
    const strip = document.getElementById('showcase');
    if (!strip) return;
    strip.textContent = '';
    SHOWCASE.forEach(function (card) {
      const b = el('button', 'showcase-card');
      b.type = 'button';
      b.appendChild(el('span', 'showcase-icon', card.icon));
      const body = el('span', 'showcase-body');
      body.appendChild(el('span', 'showcase-label', card.label));
      body.appendChild(el('span', 'showcase-tag', card.tag));
      b.appendChild(body);
      b.addEventListener('click', function () { runShowcase(card); });
      strip.appendChild(b);
    });
  }

  function runShowcase(card) {
    if (!clients) { pendingShowcase = card; attemptSignIn(); return; }
    selectAgent(card.agent);
    const ta = document.getElementById('input-' + card.agent + '-question') || composerInputs.querySelector('textarea');
    if (ta) ta.value = card.question;
    sendTask(new Event('submit'));
  }


  function buildInputs(agent) {
    composerInputs.textContent = '';
    agent.inputs.forEach(function (input) {
      const field = el('div', 'field');
      const label = el('label', null, input.label);
      label.htmlFor = 'input-' + agent.id + '-' + input.id;
      const ta = document.createElement(input.type === 'number' ? 'input' : 'textarea');
      ta.id = 'input-' + agent.id + '-' + input.id;
      if (input.type === 'number') {
        ta.type = 'number';
        ta.min = '1';
        ta.max = '43200';
        ta.step = '1';
      } else {
        ta.rows = input.rows || 3;
      }
      ta.value = input.default || '';
      const hint = el('div', 'hint', input.hint || '');
      field.appendChild(label);
      field.appendChild(ta);
      if (input.hint) field.appendChild(hint);
      composerInputs.appendChild(field);
    });
  }

  function buildNav() {
    navEl.textContent = '';
    AGENTS.forEach(function (agent) {
      const chip = el('button', 'agent-chip');
      chip.type = 'button';
      chip.style.setProperty('--chip-color', agent.color);
      chip.appendChild(el('span', 'chip-dot'));
      chip.appendChild(document.createTextNode(agent.label));
      if (agent.id === currentAgent.id) chip.classList.add('active');
      chip.addEventListener('click', function () { selectAgent(agent.id); });
      navEl.appendChild(chip);
    });
  }

  function selectAgent(id) {
    const agent = AGENTS.find(function (a) { return a.id === id; });
    if (!agent) return;
    currentAgent = agent;
    resetOutputs();
    cardTitle.textContent = agent.label;
    cardTagline.textContent = agent.tagline;
    cardOrb.style.setProperty('--card-color', agent.color);
    cardKind.textContent = agent.kind === 'research'
      ? 'Research agent — grounded answers over the corpus, with source citations.'
      : agent.kind === 'pipe'
        ? 'Pipe agent — long-lived session; events stream until you stop or the duration expires.'
        : 'Demo agent — from the A2A guide; no language model involved.';
    cardBadges.textContent = '';
    [agent.id].concat(agent.outputs).forEach(function (b) {
      cardBadges.appendChild(el('li', null, b));
    });
    buildInputs(agent);
    buildNav();
    sendBtn.disabled = false;
  }

  function onSignedIn() {
    const gate = document.getElementById('signed-out');
    const consoleEl = document.getElementById('console');
    if (gate) gate.hidden = true;
    if (consoleEl) consoleEl.hidden = false;
    selectAgent(AGENTS[0].id);
    // Free-funnel: if the user clicked a showcase card before signing in, run
    // it now (lands them directly in that agent with the question sent).
    if (pendingShowcase) {
      const card = pendingShowcase;
      pendingShowcase = null;
      runShowcase(card);
    }
  }

  // -------------------------------------------------------------------------
  // Task execution — one generic handler driven by AGENTS config
  // -------------------------------------------------------------------------

  function readInputValue(agent, inputId) {
    const ta = document.getElementById('input-' + agent.id + '-' + inputId);
    return ta ? ta.value : '';
  }

  async function sendTask(event) {
    event.preventDefault();
    const agent = currentAgent;
    const client = clients ? clients[agent.id] : null;
    if (!client) {
      authError.textContent = 'No signed-in client for ' + agent.id + '. Sign in first.';
      return;
    }

    resetOutputs();
    sendBtn.disabled = true;
    if (agent.hasStream) {
      answerArea.hidden = false;
      answerState.textContent = 'WORKING…';
      answerState.classList.add('working');
    }

    const requestParts = agent.inputs
      .filter(function (input) { return input.id !== 'duration'; })
      .map(function (input) {
        return { partId: input.id, text: readInputValue(agent, input.id) };
      });

    const renderedRefs = new Set();
    let streamedText = '';
    let session = null;
    let pipeStopped = false;

    // Pipe agents stream events continuously; show a stop button that ends
    // the session (cancels the task, closes the stream on the agent side).
    const isPipe = agent.kind === 'pipe';
    let stopBtn = null;
    if (isPipe) {
      stopBtn = el('button', 'btn btn-ghost', 'Stop stream');
      stopBtn.type = 'button';
      const actions = composer.querySelector('.composer-actions');
      if (actions) {
        stopBtn.style.marginRight = '8px';
        actions.prepend(stopBtn);
        stopBtn.addEventListener('click', function () {
          pipeStopped = true;
          stopBtn.disabled = true;
          stopBtn.textContent = 'Stopping…';
          if (session) { try { session.cancel(); } catch (_) {} }
        });
      }
    }

    try {
      const sendParams = {
        agentName: agent.id,
        requestParts,
      };
      if (isPipe) {
        const duration = parseInt(readInputValue(agent, 'duration') || '1', 10);
        sendParams.taskKind = 'pipe';
        sendParams.duration = (Number.isInteger(duration) && duration >= 1 && duration <= 43200) ? duration : 1;
      } else {
        sendParams.taskKind = 'request';
        sendParams.stream = true; // opt in to request token streaming (server default is off)
      }
      session = await client.sendMessage(sendParams);

      // Progress / status events from the agent (ctx.reportStatus).
      try {
        session.onProgress(function (ev) {
          if (ev && ev.message) setStatus(ev.message, true);
        });
      } catch (_) { /* older SDK — progress optional */ }

      // Stream (bytes, outbound) — declaredStream "_default" per card.
      if (agent.hasStream) {
        session.onStream(async function (streamRef) {
          if (streamRef.descriptor && streamRef.descriptor.declaredStream !== '_default') return;
          const stream = streamRef.open();
          try {
            for await (const chunk of stream.bytes()) {
              streamedText += new TextDecoder().decode(chunk);
              answerText.textContent = streamedText;
            }
          } catch (err) {
            answerText.textContent += '\n[stream error: ' + err.message + ']';
          }
        });
      }

      session.onArtifact(async function (event) {
        if (renderedRefs.has(event.artifactRef)) return;
        renderedRefs.add(event.artifactRef);
        let bytes;
        try {
          const downloaded = await session.downloadArtifact(event.artifactRef);
          bytes = downloaded.data;
        } catch (err) {
          answerText.textContent += '\n[download failed: ' + err.message + ']';
          return;
        }
        renderArtifact(agent, event.outputId, bytes, event.artifactRef.mimeType);
      });

      // Pipe agents: consume the live events stream as it arrives.
      if (isPipe) {
        answerArea.hidden = false;
        answerState.textContent = 'LIVE…';
        answerState.classList.add('working');
        (async function () {
          try {
            const streamRef = await session.waitForStream();
            const stream = streamRef.open();
            for await (const ev of stream.events()) {
              if (pipeStopped) break;
              if (ev && ev.type === 'paper') {
                const line = el('div', 'feed-line');
                line.appendChild(el('span', 'feed-year', String(ev.year || '')));
                const t = el('span', 'feed-title');
                t.textContent = ev.title || '';
                line.appendChild(t);
                if (ev.url) {
                  const a = el('a', 'feed-link', '↗');
                  a.href = ev.url; a.target = '_blank'; a.rel = 'noreferrer';
                  line.appendChild(a);
                }
                answerText.appendChild(line);
              } else {
                answerText.textContent += (ev ? JSON.stringify(ev) : '') + '\n';
              }
            }
          } catch (err) {
            if (!pipeStopped) answerText.textContent += '\n[stream error: ' + err.message + ']';
          }
        })();
      }

      const terminal = await session.waitForTerminal();
      if (terminal.state === 'completed') {
        if (agent.hasStream || isPipe) {
          answerState.textContent = isPipe ? 'ENDED' : 'COMPLETE';
          answerState.classList.remove('working');
          answerState.style.color = '';
        }
        setStatus('', false);
      } else if (isPipe && terminal.state === 'canceled') {
        // User clicked "Stop stream" — a normal end for a pipe session.
        answerState.textContent = 'STOPPED';
        answerState.classList.remove('working');
        answerState.style.color = '';
        setStatus('', false);
      } else {
        const reason = terminal.error || terminal.reason || 'task ' + terminal.state;
        setStatus('', false);
        if (agent.hasStream || isPipe) {
          answerState.textContent = 'FAILED';
          answerState.classList.remove('working');
          answerState.style.color = '#fb7185';
          answerText.textContent += '\n[' + reason + ']';
        } else {
          demoText.textContent = 'Error: ' + reason;
          demoArea.hidden = false;
        }
      }

      // Defensive fallback: any artifact not seen via onArtifact.
      for (const ref of session.listArtifacts()) {
        if (renderedRefs.has(ref)) continue;
        renderedRefs.add(ref);
        try {
          const downloaded = await session.downloadArtifact(ref);
          renderArtifact(agent, ref.outputId || null, downloaded.data, ref.mimeType);
        } catch (err) {
          answerText.textContent += '\n[download failed: ' + err.message + ']';
        }
      }
    } catch (err) {
      setStatus('', false);
      if (agent.hasStream || isPipe) {
        answerState.textContent = 'ERROR';
        answerState.classList.remove('working');
        answerState.style.color = '#fb7185';
        answerText.textContent += '\n[' + blocksErrorMessage(err) + ']';
      } else {
        demoText.textContent = blocksErrorMessage(err);
        demoArea.hidden = false;
      }
    } finally {
      if (stopBtn) stopBtn.remove();
      if (session) { try { await session.asyncClose(); } catch (_) {} }
      sendBtn.disabled = false;
    }
  }

  function renderArtifact(agent, outputId, bytes, mimeType) {
    const text = new TextDecoder().decode(bytes);
    const id = outputId || '';

    // A2A demo trio — single output → demo panel.
    if (agent.kind === 'demo' && agent.id !== 'star_map_demo') {
      demoArea.hidden = false;
      if (id === 'echo') {
        demoText.textContent = text;
      } else {
        try { demoText.textContent = JSON.stringify(JSON.parse(text), null, 2); }
        catch (_) { demoText.textContent = text; }
      }
      return;
    }

    // star_map_demo — cache each piece and re-render in fixed order (answer
    // text then download link) so arrival order can't clobber either.
    if (agent.id === 'star_map_demo') {
      if (id === 'answer') starMapDemoCache.answer = text;
      if (id === 'demo') starMapDemoCache.html = bytes;
      renderStarMapDemo();
      return;
    }

    switch (id) {
      case 'answer': {
        answerArea.hidden = false;
        answerState.textContent = '';
        answerState.classList.remove('working');
        // The terminal answer artifact is authoritative; replace streamed text.
        answerText.textContent = '';
        answerText.textContent = text;
        lastAnswerText = text;
        markCitations(answerText);
        break;
      }
      case 'sources': {
        let data;
        try { data = JSON.parse(text); } catch (_) { data = null; }
        if (data) renderSources(data);
        break;
      }
      case 'summary': {
        // Pipe agent's terminal session summary.
        reportArea.hidden = false;
        try { reportText.textContent = JSON.stringify(JSON.parse(text), null, 2); }
        catch (_) { reportText.textContent = text; }
        break;
      }
      case 'report':
      case 'review':
      case 'draft':
      case 'subgraph':
      case 'skeleton':
      case 'ada': {
        // Structured JSON artifacts (orchestrator report, lit_review review,
        // grant draft, graph subgraph, code skeleton) share the report panel.
        reportArea.hidden = false;
        try { reportText.textContent = JSON.stringify(JSON.parse(text), null, 2); }
        catch (_) { reportText.textContent = text; }
        break;
      }
      default: {
        // Untagged artifact — best-effort by mime.
        const scratch = el('div');
        scratch.className = 'report-text';
        renderArtifactByMime(bytes, mimeType, scratch);
        if (scratch.textContent) {
          answerArea.hidden = false;
          answerText.textContent += scratch.textContent;
        }
      }
    }
  }

  // star_map_demo render state — survives artifact arrival order.
  const starMapDemoCache = { answer: null, html: null };

  function renderStarMapDemo() {
    if (starMapDemoCache.answer == null && starMapDemoCache.html == null) return;
    answerArea.hidden = false;
    answerText.textContent = '';
    if (starMapDemoCache.answer != null) {
      answerText.textContent = starMapDemoCache.answer;
      markCitations(answerText);
    }
    if (starMapDemoCache.html != null) {
      const blob = new Blob([starMapDemoCache.html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'star-map-demo.html';
      a.textContent = '⬇ Download star-map-demo.html (interactive 3D star map)';
      a.className = 'detail-link';
      answerText.appendChild(a);
    }
  }

  // Reset the demo cache when switching agents or sending a new task.
  function resetStarMapDemo() {
    starMapDemoCache.answer = null;
    starMapDemoCache.html = null;
  }

  composer.addEventListener('submit', sendTask);

  // Enter to send (Shift+Enter for newline) on the first textarea.
  composerInputs.addEventListener('keydown', function (event) {
    if (event.key === 'Enter' && !event.shiftKey) {
      const first = composerInputs.querySelector('textarea');
      if (first && event.target === first && !sendBtn.disabled) {
        event.preventDefault();
        sendTask(event);
      }
    }
  });

  // Export + showcase + free-funnel wiring.
  const exportBibBtn = document.getElementById('export-bib-btn');
  const exportCsvBtn = document.getElementById('export-csv-btn');
  const copyBriefBtn = document.getElementById('copy-brief-btn');
  if (exportBibBtn) exportBibBtn.addEventListener('click', exportBibtex);
  if (exportCsvBtn) exportCsvBtn.addEventListener('click', exportCsv);
  if (copyBriefBtn) copyBriefBtn.addEventListener('click', copyBrief);

  const gateDemoBtn = document.getElementById('gate-demo-btn');
  if (gateDemoBtn) {
    gateDemoBtn.addEventListener('click', function () {
      pendingShowcase = { agent: 'star_map_demo', question: 'Show me the demo' };
      attemptSignIn();
    });
  }

  buildShowcase();

  // The answer-meta row right-aligns its Copy brief button.
  const copyBriefEl = document.getElementById('copy-brief-btn');
  if (copyBriefEl) copyBriefEl.style.marginLeft = 'auto';

  // A11y: expose auth state
  const authState = document.getElementById('auth-state');
  if (authState) {
    authState.textContent = 'Signed in';
    authState.hidden = false;
  }

})();
